# managed (in part) by pyprojkit: https://github.com/mm21/pyprojkit

[project]
authors = [
  {name = "mm21", email = "mm21.dev@gmail.com"}
]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Natural Language :: English",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3",  # pyprojkit-managed
  "Programming Language :: Python :: 3.12",  # pyprojkit-managed
  "Programming Language :: Python :: 3.13",  # pyprojkit-managed
  "Programming Language :: Python :: 3.14",  # pyprojkit-managed
  "Programming Language :: Python :: Implementation :: CPython",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Typing :: Typed"
]
dependencies = [
  "doit>=0.36.0,<0.37",
  "nox>=2026.4.10",
  "python-dotenv>=1.0.1,<2",
  "toml-sort>=0.24.2,<0.25",
  "tomlkit>=0.13.3,<0.14"
]
description = "Development workflow toolkit for Python projects: pyproject.toml sync, doit tasks, nox sessions"
license = "MIT"
license-files = ["LICENSE"]
name = "pyprojkit"
readme = "README.md"
requires-python = ">=3.12,<3.15"  # pyprojkit-managed
version = "0.3.1"

[project.optional-dependencies]
all = [
  "pyprojkit[analysis,doc,format,test]"
]
analysis = [
  "mypy[reports]>=1.5.1,<2",
  "pyright>=1.1.329,<2"
]
doc = [
  "mkinit"
]
format = [
  "autoflake>=2.3.1,<3",
  "black>=25.1.0,<26",
  "docfmt>=0.2.0,<0.3.0",
  "isort>=6.0.1,<7"
]
test = [
  "genbadge[tests,coverage]>=1.1.0,<2",
  "pytest>=8.4.2,<9",
  "pytest-cov>=7.1.0"
]

[project.scripts]
pyprojkit = "pyprojkit.cli:main"

[project.urls]
homepage = "https://github.com/mm21/pyprojkit"

[dependency-groups]
dev = [
  "pyprojkit[all]"
]

[build-system]
build-backend = "uv_build"
requires = ["uv_build>=0.11.6,<0.12.0"]

[tool.autoflake]
in_place = true  # pyprojkit-managed
recursive = true  # pyprojkit-managed
remove-all-unused-imports = true  # pyprojkit-managed
remove-unused-variables = true  # pyprojkit-managed

[tool.black]
quiet = true  # pyprojkit-managed
target-version = [
  "py312",
  "py313",
  "py314"
]  # pyprojkit-managed

[tool.coverage.report]
exclude_lines = [
  "if TYPE_CHECKING:",
  "\\.\\.\\.$"
]  # pyprojkit-managed

[tool.coverage.run]
data_file = "__cache__/.coverage"  # pyprojkit-managed

[tool.docfmt]
force-reflow = true  # pyprojkit-managed
in-place = true  # pyprojkit-managed
recursive = true  # pyprojkit-managed
summary-on-own-line = true  # pyprojkit-managed

[tool.doit]
dep_file = "__cache__/.doit.db"  # pyprojkit-managed
verbosity = 2  # pyprojkit-managed

[tool.isort]
profile = "black"  # pyprojkit-managed
quiet = true  # pyprojkit-managed

[tool.nox]
default_venv_backend = "uv"  # pyprojkit-managed
envdir = "__cache__/nox"  # pyprojkit-managed

[tool.pytest.ini_options]
addopts = "--import-mode=importlib -s -v -rA"  # pyprojkit-managed
cache_dir = "__cache__/pytest"  # pyprojkit-managed
testpaths = "test"  # pyprojkit-managed

[tool.tomlsort]
sort_first = [
  "project",
  "dependency-groups",
  "build-system"
]  # pyprojkit-managed
sort_table_keys = true  # pyprojkit-managed
spaces_before_inline_comment = 2  # pyprojkit-managed

[tool.uv.sources]
mkinit = {git = "https://github.com/mm21/mkinit.git"}
